### PR TITLE
Opt-in to use the new GDS API Adapters behaviour

### PR DESCRIPTION
**Pull request by issyl0**
- Trello: https://trello.com/c/B5z6Dq8q/495.

### CODE REVIEW

**Review by brenetic — CHANGES_REQUESTED** [review]
Looks good!

Can we just add a little more to the commit/PR message please

**Review by brenetic — APPROVED** [review]

**Review by davidbasalla — COMMENTED** [review]
First day back from hols here, so I may have the wrong end of the stick here 😁

I was expecting that we would have to update some of our code to catch the possible Exceptions coming from GdsApi adapters with this change. Looking at the code, it looks like we only use the mapit adapter from GdsApiAdapters. So wondering whether we should do any work [here](https://github.com/alphagov/local-links-manager/blob/master/lib/local-links-manager/import/local_authorities_importer.rb#L94-L96) to catch exceptions that could now be thrown. Afaik previously a 404 or 410 response would have just returned `nil` here but now a Exception would just make stop code execution entirely?

However... we seem to be [rescuing in the Processor class](https://github.com/alphagov/local-links-manager/blob/master/lib/local-links-manager/import/processor.rb#L34) anyway, so probably everything is fine and will work anyway... so no changes needed, just me talking out loud :)

**Comment by issyl0** [comment]
Interesting. I'd have expected some test failures if other things needed changing, but given we're rescuing everything, that probably explains it. I'll work out what to explicitly rescue for 404s and 410s, if I can.

**Comment by davidbasalla** [comment]
Had another look through with @emmabeynon and think this looks good as is!

**Pull request merged**
