### PR TITLE
Add Capistrano deployment

### PR DESCRIPTION
**Pull request by alexmuller**
This is copied from alphagov-deployment.

@brenetic @emmabeynon @klssmith

### CODE REVIEW

**Comment by boffbowsh** [comment]
Why is this being configured in the repo instead of alphagov-deployment?

**Comment by alexmuller** [comment]
Incoming pull request on alphagov/govuk-puppet to explain.

**Comment by alexmuller** [comment]
alphagov/govuk-puppet#4344

**Comment by boffbowsh** [comment]
👍

**Comment by alexmuller** [comment]
I think we're going to take a different approach for this!

**Pull request closed without merging**
